# Generated by Django 4.1.1 on 2022-09-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bb',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bb',
            old_name='content',
            new_name='owner',
        ),
    ]
